version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 673681791273.dkr.ecr.ap-southeast-2.amazonaws.com/assessment2)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI=673681791273.dkr.ecr.ap-southeast-2.amazonaws.com/assessment2:${IMAGE_TAG}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"my-node-container","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json


